### ISSUE TITLE
An introduction

### ISSUE THREAD

**Issue by santigimeno** [cdesiles/node-pcsc#10]
Hello,

First of all, thanks for publishing this project.

Just a brief introduction: a year ago I started a small module with bindings to pcsclite but never got to publish it. A couple of weeks ago I found out about your project and finally decided to clean up my code and finally publish it. Here it is: https://github.com/santigimeno/node-pcsclite. Its philosophy is a little different from yours as it uses threads instead of processes to execute the blocking operations. It's only a small project and by no means complete but maybe, if you're interested, we could merge efforts to have only one and more complete pcsc module. What do you think?

Best regards,

Santi

**Comment by cdesiles** [comment]
Thank you Santi,
I would be glad to share the same efforts, for sure. The project was actually in a stand-by state, because I do not have more time to spend on it at work. But lastly I've received my own smart-card/RFID reader, so I'm able to pursue the adventure =)

I'll have a look at your project soon, and I'll give you updated.

Jk.

**Comment by cdesiles** [comment]
Hi Santi,
I 've tested your module yesterday, and I really like your approach. I feel `node-pcsclite` is much more promising by its eventful binding approach than `node-pcsc` is.

For now I could not figure out how to detect my multiple card readers, and to get the ATR of an inserted card. I did not have time to look for further information for now, but I will write more examples if I get the point.
Also please let me now if need anything to develop/add/fix on your project.

**Comment by santigimeno** [comment]
@jokesterfr 
Thanks for your feedback!

The problems you're having detecting multiple card readers and the ATR of the card are with my module or yours?

For sure I'll let you know! I plan to use this module in production real soon, I'm sure bugs will appear.

Regards

Santi

**Comment by cdesiles** [comment]
I was speaking about yours

**Comment by santigimeno** [comment]
Ok. I thought that was supported. I'll test and let you  know

**Comment by cdesiles** [comment]
I'm closing this thread, I'll open issues directly in `node-pcsclite` project if needed.
