### ISSUE TITLE
Client Side Javascript accessing client-connected devices

### ISSUE THREAD

**Issue by brunobertechini** [cdesiles/node-pcsc#19]
Hi there nice project...

Is this project goal to enable client side javascript to access client-connected pcsc devices?

I mean, it runs on node.js at the server, but the javascript at local client would be able to connect to SmartCard readers connected to client computer (running browser) ?

Bruno

**Comment by cdesiles** [comment]
Hi Bruno,
this project is intended to support PCSC devices from Javascript, but server-side (Node.js). However you can easily send messages to your browser through a websocket connection for instance.

**Comment by brunobertechini** [comment]
Ok Thanks
