### ISSUE TITLE
Mac OS X port: error: array initializer must be an initializer list

### ISSUE THREAD

**Issue by LudovicRousseau** [cdesiles/node-pcsc#2]
Compilation fail on Mac OS X:

```
../src/pcsc-client.cc:313:24: error: array initializer must be an initializer list
                v8::Local<v8::Value> argv[argc] = NULL;
```

I have no idea how to fix that.

**Comment by cdesiles** [comment]
I'm sorry my purpose was not to support Max OSX at first. In your [PCSC sample in C](http://ludovicrousseau.blogspot.fr/2010/04/pcsc-sample-in-c.html) you specified some Mac OSX code I chose not to reproduce, to get code as simple as possible.

In your case, I think the compiler is expecting something like:

``` .bash
 v8::Local<v8::Value> argv[argc] = {};
```

Let me know

**Comment by LudovicRousseau** [comment]
Exact. I do not have the error any more with this change.

Please commit this change if it has no impact on GNU/Linux.

**Comment by cdesiles** [comment]
Are you still experiencing troubles on Max OS X?
Please notify me if I forgot to merge any of your contributions regarding this point.

**Comment by LudovicRousseau** [comment]
It looks like it is OK now.
