### ISSUE TITLE
src/pcsc-client.cc:323:2: warning: control reaches end of non-void function

### ISSUE THREAD

**Issue by LudovicRousseau** [cdesiles/node-pcsc#4]
I have the warning: src/pcsc-client.cc:323:2: warning: control reaches end of non-void function

The code is:

```
    /**
     * Release the PCSC context
     */
    int release_context ( SCARDCONTEXT &hContext ){
         SCardReleaseContext(hContext);
    }
```

The function shall return a value.
I don't know which one.

**Comment by cdesiles** [comment]
I took your fix, as of merge request #9, closed now
